package com.dnchia.grpc;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * Instantiates a GRPC server. This is done by using the @GrpcService annotation and implementing the service
 * previously generated by the GRPC integration.
 *
 * Note that the application must be compiled to get CalculatorServiceGrpc.CalculatorServiceImplBase on
 * CalculatorService.
 */
@SpringBootApplication
public class GrpcServerApplication {

	public static void main(String[] args) {
		SpringApplication.run(GrpcServerApplication.class, args);
	}
}